######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 29 20:28:42 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += g_class.h log.h tabl_class.h
SOURCES += g_class.cpp log.cpp main.cpp tabl_class.cpp
