######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 25 21:49:57 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
