bus: main.o luru.o shanchu.o liulan.o chaxun.o xiugai.o gengxin.o jiazai.o
	cc -o bus main.o luru.o shanchu.o liulan.o chaxun.o xiugai.o gengxin.o jiazai.o
main.o: main.c xitong.h
	cc -c main.c 
luru.o: luru.c xitong.h
	cc -c luru.c 
shanchu.o: shanchu.c xitong.h
	cc -c shanchu.c 
liulan.o: liulan.c xitong.h
	cc -c liulan.c 
chaxun.o: chaxun.c xitong.h
	cc -c chaxun.c 
xiugai.o: xiugai.c xitong.h
	cc -c xiugai.c 
gengxin.o: gengxin.c xitong.h
	cc -c gengxin.c 
jiazai.o: jiazai.c xitong.h
	cc -c jiazai.c 

