######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 26 20:39:57 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += log.cpp
