######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 27 11:19:46 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
