######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 27 18:41:56 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += g_class.h tabl_class.h
SOURCES += g_class.cpp main.cpp tabl_class.cpp
