######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 30 00:40:41 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += untitled.ui
